version: '3.8'

services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot-enhanced
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./session_data:/app/session_data
      - ./bot_data:/app/bot_data
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

